# ***#theory questions***

1.explain the purpose and advantages of numpy in scientific computing and data analysis.how does it enhance python's capabilities for numerical operations.

ans:-NumPy is a Python library fundamental for scientific computing and data analysis.

Purpose and Advantages

NumPy introduces the ndarray (n-dimensional array) object for efficient storage and manipulation of homogeneous data. It is faster to access and manipulate NumPy arrays compared to native Python lists, as data is stored contiguously in memory, improving performance. NumPy offers a wide array of mathematical functions that can be applied directly to these arrays, eliminating the need for explicit loops. This vectorization enables concise and efficient expression of complex calculations.
NumPy enables the broadcasting feature, which allows operations between arrays of different shapes under specific rules, further simplifying code and enhancing flexibility. It provides tools for linear algebra, Fourier transforms, and random number generation, which are essential in scientific computing and data analysis workflows.
Enhancing Python's Capabilities

NumPy empowers Python by introducing an array object that is more suitable and optimized for numerical computations than native Python lists. It facilitates efficient storage and retrieval of data through the ndarray, and leverages vectorization, avoiding the overhead of explicit loops for numerical operations, leading to significant performance gains.
Overall, NumPy's role is pivotal in scientific computing and data analysis with Python. Its functionalities like the efficient ndarray, a vast collection of mathematical functions, broadcasting, and tools for advanced mathematical operations make it an indispensable library for researchers, scientists, and data analysts.


2.compare and contrast np.mean ()and np.average() function in numpy.when would you use one over the other.

ans:-np.mean() and np.average() in NumPy:

Similarities

Both functions calculate the average (arithmetic mean) of elements in an array. When used with default parameters, they produce the same output.
Differences

np.average() allows for weighted averaging using the weights parameter, enabling different elements to contribute differently to the average. np.mean() does not offer this functionality directly.
When to Use Which

Use np.mean() when calculating the simple arithmetic mean of an array without considering any weights for the elements.
Use np.average() when calculating the weighted average of an array, where different elements have different weights assigned to them influencing the final average.

3.describes the method for reversing a numpoy array alohg different axes.provide example for 1d and 2d arrays.

ans:-Method

Use the numpy.flip() function to reverse an array along specified axes. The axis parameter determines which axis or axes to reverse. For example, axis=0 reverses along the first axis (rows), and axis=1 reverses along the second axis (columns). If axis is not specified, the array is flipped along all axes.

Example: 1D Array


import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = np.flip(arr)  # Reverses along the only axis
Use code with caution
Example: 2D Array


import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Reverse along rows (axis=0)
reversed_rows = np.flip(arr, axis=0)

# Reverse along columns (axis=1)
reversed_cols = np.flip(arr, axis=1)
Use code with caution
In these examples, reversed_arr will contain the reversed 1D array, reversed_rows will contain the 2D array with rows reversed, and reversed_cols will contain the 2D array with columns reversed

4.how can you determine the data type of elements in a  numpy array .discuss the importance of data types in memory management and performance.

ans:-the data type of elements in a NumPy array and the importance of data types:

Determining Data Type

Use the dtype attribute of a NumPy array to determine the data type of its elements.


import numpy as np

arr = np.array([1, 2, 3])
data_type = arr.dtype  # Accessing the data type
Use code with caution
Importance of Data Types

Memory Management: Data types influence the amount of memory allocated to store each element in an array. Choosing an appropriate data type helps optimize memory usage and reduce memory footprint. For instance, if you're working with integers that fall within a specific range, using int16 instead of int64 can save significant memory space.

Performance: Data types impact the performance of numerical computations. Operations on arrays with matching data types are generally faster. Type casting and conversions during computations can introduce overhead, affecting performance. NumPy's optimized functions often work best with specific data types, such as float64 for floating-point calculations.

By carefully selecting and managing data types in NumPy arrays, you can ensure efficient memory usage and improve the performance of your numerical computations.

5.define ndarrays in numpy and explain their key feature .how do they differ from standard python list.

ans:-Definition

In NumPy, an ndarray (n-dimensional array) is a homogeneous multidimensional container of items of the same data type. It's the fundamental data structure in NumPy for representing and manipulating numerical data.

Key Features

Homogeneous Data: All elements in an ndarray have the same data type, ensuring efficient storage and operations.
Multidimensional: ndarrays can represent data in multiple dimensions, allowing for the creation of vectors, matrices, and higher-dimensional arrays.
Element-wise Operations: NumPy provides functions that operate element-wise on ndarrays, making numerical computations concise and efficient.
Broadcasting: NumPy's broadcasting rules allow operations between arrays of different shapes under certain conditions, simplifying code and enhancing flexibility.
Differences from Standard Python Lists

Homogeneity: ndarrays are homogeneous, while Python lists can contain elements of different data types.
Element-wise Operations: NumPy supports efficient element-wise operations on ndarrays, whereas Python lists require explicit loops for such computations.
Memory Efficiency: ndarrays are more memory-efficient than Python lists, especially for large datasets, due to their contiguous storage and homogeneous data types.
Functionality: NumPy provides a vast library of functions for numerical and scientific computing, extending the capabilities of standard Python lists.

6.analize the performance benefits of numpy arrays over python lists for large-scale numerical operations,.

ans:-Performance Benefits

Vectorization: NumPy arrays support vectorized operations, allowing mathematical functions to be applied to entire arrays without explicit loops. This significantly speeds up computations compared to iterating over elements in Python lists.
Contiguous Memory: NumPy arrays store data in contiguous memory locations, enabling efficient access and manipulation of elements. Python lists, on the other hand, store pointers to objects scattered in memory, leading to performance overhead.
Data Type Optimization: NumPy arrays use fixed data types for elements, allowing for optimized operations specific to those types. Python lists have more flexible data types, but this flexibility can introduce overhead in numerical computations.
Specialized Functions: NumPy provides a vast library of specialized functions for numerical and scientific computing, optimized for performance. Python lists lack these specialized functions, requiring manual implementation or reliance on less efficient alternatives.
Impact on Large-Scale Operations

For large-scale numerical operations, the performance benefits of NumPy arrays become even more significant. The reduced overhead from vectorization, contiguous memory, and optimized functions translates into substantial time savings and improved efficiency. NumPy arrays are designed to handle large datasets efficiently, making them the preferred choice for scientific computing and data analysis tasks.

7.compare vstack ()and hstack() functions in numpy.provide examples demonstrating their usage and output.

ans:-vstack()

Vertically stacks arrays.
Arrays are stacked along the first axis (rows).
The number of columns in the arrays must be the same.
Example


import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked = np.vstack((a, b))  # Vertical stacking
Use code with caution
hstack()

Horizontally stacks arrays.
Arrays are stacked along the second axis (columns).
The number of rows in the arrays must be the same.
Example


import numpy as np

a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

stacked = np.hstack((a, b))  # Horizontal stacking
Use code with caution
Execute the code yourself to see the output. Choose the stacking function (vstack or hstack) that aligns with your desired stacking direction (vertical or horizontal) and the shape of your arrays.

8.explain the differences between fliplr() and filpud() methods in numpy. including their effacts oh various array dimensions.

ans:-fliplr()

Flips an array horizontally (left to right).
Reverses the order of elements along the second axis (columns).
Primarily used for 2D arrays.
For 1D arrays, it behaves similarly to flipud().
flipud()

Flips an array vertically (up to down).
Reverses the order of elements along the first axis (rows).
Primarily used for 2D arrays.
For 1D arrays, it behaves similarly to fliplr().
Effects on Array Dimensions

1D Arrays: Both fliplr() and flipud() have the same effect on 1D arrays, simply reversing the elements.
2D Arrays: fliplr() flips the array horizontally, reversing the columns, while flipud() flips the array vertically, reversing the rows.
Example


import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

flipped_lr = np.fliplr(arr)  # Horizontal flip
flipped_ud = np.flipud(arr)  # Vertical flip
Use code with caution
Execute the code yourself to see the output. Remember that fliplr() is typically used to flip 2D arrays horizontally, while flipud() is used to flip them vertically. For 1D arrays, they have the same effect

9.discuss the functionality of the array_spilt ()method in numpy . how does it handle uneven splits.

ans:-Functionality

Splits an array into multiple sub-arrays along a specified axis.
The number of sub-arrays is determined by the indices_or_sections parameter.
Handles uneven splits by distributing the remaining elements as evenly as possible among the sub-arrays.
Handling Uneven Splits

When the array cannot be divided evenly into the specified number of sub-arrays, array_split() distributes the remaining elements among the sub-arrays to minimize the difference in their sizes.

Example


import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Split into 3 sub-arrays
sub_arrays = np.array_split(arr, 3)
Use code with caution
In this example, array_split() will create 3 sub-arrays: [1, 2, 3], [4, 5, 6], and [7, 8]. The remaining two elements are distributed to the last two sub-arrays to achieve a relatively balanced split.

Execute the code yourself to see the output. Consider using array_split() when you need to split an array into a specific number of sub-arrays, even if the split is uneven.

10.explaim the concepts of vectorization and broadcasting in numpy. how do they contribute to efficient array operations.

ans:-Okay, let's explain vectorization and broadcasting in NumPy:

Vectorization

Performing operations on entire arrays instead of individual elements using loops.
NumPy functions are designed to operate on arrays directly, eliminating the need for explicit loops.
Leads to significant performance improvements, especially for large arrays.
Broadcasting

Extending the concept of vectorization to arrays with different shapes.
NumPy's broadcasting rules allow operations between arrays with compatible shapes, even if they don't have the same dimensions.
Simplifies code and enhances flexibility in array operations.
Contribution to Efficient Array Operations

Reduced Loops: Vectorization and broadcasting minimize the need for explicit loops, reducing the overhead of iterating over elements individually.
Optimized Operations: NumPy functions are optimized for array operations, leveraging low-level implementations for efficient execution.
Concise Code: Vectorization and broadcasting allow for more concise and expressive code, making it easier to write and understand complex numerical operations.
Example


import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b  # Vectorized addition
Use code with caution
In this example, the + operator is applied element-wise to the entire arrays a and b, resulting in a new array c without explicit loops. This is vectorization in action. Broadcasting would come into play if a and b had different shapes but were compatible according to NumPy's broadcasting rules.

By leveraging vectorization and broadcasting, NumPy enables efficient and concise array operations, making it a powerful tool for numerical computations.


# ***practical question ***


1.create a 3*3 numpy array with random integers between 1 and 100. then interchange its rows and columns.


In [1]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))

# Interchange rows and columns using transpose()
transposed_array = array.transpose()

# Print the original and transposed arrays
print("Original array:")
print(array)
print("\nTransposed array:")
print(transposed_array)

Original array:
[[72 42 57]
 [23 77 55]
 [ 3 45 45]]

Transposed array:
[[72 23  3]
 [42 77 45]
 [57 55 45]]


2.genrate a 1D numpy array with 10 elements . reshape it into 2*5 aray then into a 5*2.


In [2]:
import numpy as np

# Create a 1D array with 10 elements
array_1d = np.arange(10)

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)

# Print the arrays
print("Original 1D array:")
print(array_1d)
print("\nReshaped 2x5 array:")
print(array_2x5)
print("\nReshaped 5x2 array:")
print(array_5x2)

Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3.create a 4*4 numjpy array with random floot values .add a border of xeros around  it resulting in a 6*6 array.


In [3]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros using pad
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

# Print the arrays
print("Original 4x4 array:")
print(array_4x4)
print("\n6x6 array with border of zeros:")
print(array_6x6)

Original 4x4 array:
[[0.40440751 0.52222395 0.61976086 0.63436673]
 [0.69197124 0.95404589 0.64691795 0.10338327]
 [0.44509027 0.40251131 0.99203784 0.22786188]
 [0.56765278 0.45256571 0.64976795 0.80393078]]

6x6 array with border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.40440751 0.52222395 0.61976086 0.63436673 0.        ]
 [0.         0.69197124 0.95404589 0.64691795 0.10338327 0.        ]
 [0.         0.44509027 0.40251131 0.99203784 0.22786188 0.        ]
 [0.         0.56765278 0.45256571 0.64976795 0.80393078 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4.using numpy,create an array of integers from 10 to 60 with a step of 5.


In [4]:
import numpy as np

array = np.arange(10, 61, 5)
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


5.create a numpy array of string [python ,numpy , pandas ]. apply  different case

In [5]:
import numpy as np

# Create the array
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case conversions
lowercase = np.char.lower(arr)
uppercase = np.char.upper(arr)
titlecase = np.char.title(arr)
swapcase = np.char.swapcase(arr)

# Print the results
print("Original array:", arr)
print("Lowercase:", lowercase)
print("Uppercase:", uppercase)
print("Titlecase:", titlecase)
print("Swapcase:", swapcase)

Original array: ['python' 'numpy' 'pandas']
Lowercase: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Titlecase: ['Python' 'Numpy' 'Pandas']
Swapcase: ['PYTHON' 'NUMPY' 'PANDAS']


6.genrate a numpy array  of words. insert a space between each character of every word in the array.


In [6]:
import numpy as np

# Create a NumPy array of words
words = np.array(['hello', 'world', 'numpy'])

# Insert a space between each character
spaced_words = np.char.join(' ', words)

# Print the result
print(spaced_words)

['h e l l o' 'w o r l d' 'n u m p y']


7.create two 2D numpy arrays and perform elements-wise addition,subtraction, multiplication , and dividion.

In [7]:
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

# Print the results
print("Array 1:\n", array1)
print("\nArray 2:\n", array2)
print("\nAddition:\n", addition)
print("\nSubtraction:\n", subtraction)
print("\nMultiplication:\n", multiplication)
print("\nDivision:\n", division)

Array 1:
 [[1 2 3]
 [4 5 6]]

Array 2:
 [[ 7  8  9]
 [10 11 12]]

Addition:
 [[ 8 10 12]
 [14 16 18]]

Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]

Multiplication:
 [[ 7 16 27]
 [40 55 72]]

Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


8.use numpyto create a 5*5 identity matrix then extracts its diagonal elements .


In [8]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

# Extract diagonal elements
diagonal_elements = np.diag(identity_matrix)

# Print the results
print("Identity matrix:\n", identity_matrix)
print("\nDiagonal elements:", diagonal_elements)

Identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal elements: [1. 1. 1. 1. 1.]


9.genrate a numpy array of 100 random integers between 0 and 1000. find and display all primes numbers in this array.

In [9]:
import numpy as np

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Generate random integers
random_integers = np.random.randint(0, 1001, size=100)

# Find prime numbers
prime_numbers = [num for num in random_integers if is_prime(num)]

# Display prime numbers
print("Prime numbers in the array:", prime_numbers)

Prime numbers in the array: [107, 569, 389, 719, 499, 89, 673, 313, 109, 383, 503, 571, 23, 479, 397, 947, 947, 251, 163, 347, 179]


10.create a numpy array representing daily temperature for a month .  calculate and display the weekly average.  



In [10]:
import numpy as np

# Assume 30 days in the month
daily_temperatures = np.random.randint(20, 35, size=30)  # Example temperatures

# Reshape for weekly averages (4 weeks + 2 extra days)
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)

# Calculate weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

# Display the results
print("Daily Temperatures:", daily_temperatures)
print("\nWeekly Averages:", weekly_averages)

Daily Temperatures: [25 23 33 27 25 29 33 34 20 29 32 28 23 33 23 30 20 22 25 20 21 21 34 25
 32 30 21 22 30 27]

Weekly Averages: [27.85714286 28.42857143 23.         26.42857143]
